# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8fe5d64689afb01225b4408bc108bd8a"
name = "delivery-count"
application_url = "https://delivery-count.onrender.com"
embedded = true


[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products,read_orders,write_orders"

[app_proxy]
url = "https://delivery-count.onrender.com/proxy/de-count"
subpath = "de-count"
prefix = "apps"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]
  
  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"
[auth]
redirect_urls = [ "https://delivery-count.onrender.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
